### ISSUE TITLE
Detect Cycle in a Directed Graph

### ISSUE THREAD

**Issue by HARSH-nith** [HARSH-nith/DSA#20]
write a program in c++ to detect cycle in a directed graph

**Comment by Kartik7Dhiman** [comment]
Please assign this to me.

**Comment by Debayan97531** [comment]
please assign this to me.. @HARSH-nith

**Comment by HARSH-nith** [comment]
okay

**Comment by Debayan97531** [comment]
I have added the code for this issue.Will you kindly merge it??

**Comment by Debayan97531** [comment]
#62
