### ISSUE TITLE
Quick sort in linked list

### ISSUE THREAD

**Issue by HARSH-nith** [HARSH-nith/DSA#23]
Write a program to implement quick sort in  linked list

**Comment by Sourz-101** [comment]
Working on this issue
please me this

**Comment by Sourz-101** [comment]
Created a PR on this issue
Please accept my PR under the label of hacktoberfest-accepted.
Thankyou :)

**Comment by Debayan97531** [comment]
hi @HARSH-nith can you please assign this to me??..I can do it

**Comment by HARSH-nith** [comment]
okay
