### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by HARSH-nith** [HARSH-nith/DSA#4]
Write a C++ program to implement selection sort

**Comment by Anish-Sarawgi** [comment]
I Want to work on this issue. Can you please assign it to me?

**Comment by HARSH-nith** [comment]
ok

**Comment by Anish-Sarawgi** [comment]
Hey @HARSH-nith,
I have added the required source code. Please merge it in the repository.

### Please add the Hacktoberfest and Hacktoberfest-Accepted tags in my PR.
