### ISSUE TITLE
Implement counting sort

### ISSUE THREAD

**Issue by ilimugur** [HARSH-nith/DSA#56]
As one of the few well-known non-comparative sorting algorithms, it's beneficial if Counting sort is also featured in the repository.

**Comment by Sajal193** [comment]
Hi @ilimugur . can you please assign this issue to me if it's open?

**Comment by ilimugur** [comment]
@Sajal193 Not really, 'cause (a) while I reported the issue, I don't have those privileges for this repository and (b) my pull request with the implementation was already merged.

That said, while I initially thought that @HARSH-nith would close the issue after merging my PR, it might be best if I close it to avoid further misunderstanding.
